### ISSUE TITLE
[BUG] International feed not downloadable

### ISSUE THREAD

**Issue by kimisecond** [SoMuchForSubtlety/f1viewer#234] opened 2022-04-08 09:33 UTC
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Tried all International feed this season, it came up with an **ERROR**: 'could not get video URL: Video FER URL From Additional Streams - 7006 - 1025-No Data Found in DB'(e.g. this was the error message I got when clicking download for 2022 Australian GP FP1).
The actual International Feed seems to be the 'Default' channel in the list.

**To Reproduce**
1. Select International feed
2. Try to Download it or open it with any player or copy the URL

**Expected behaviour**
Play feed/Download feed/Copy URL

**Screenshots**

**F1TV account plan**
Pro Account. w&wo VPN

**Desktop (please complete the following information):**
 - macOS
 - Brew
 - 2.7.0

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by Michael-LY** [comment] 2022-04-08 10:01
Encountered the same issue using Win64 desktop client.

**Comment by SoMuchForSubtlety** [comment] 2022-04-08 11:37
You should be able to download the "Default" feed.

**Comment by kimisecond** [comment] 2022-04-08 11:51
> You should be able to download the "Default" feed.

Yes, the 'Default" one is downloadable.

**Comment by Vallesuski** [comment] 2022-04-08 17:58
Were you able to download Practice 2 from Australia? I get a gray screen, is corrupted.

**Comment by kimisecond** [comment] 2022-04-10 11:01
> Were you able to download Practice 2 from Australia? I get a gray screen, is corrupted.

I'm able to do it now, but not right after FP2. Maybe there's some timer to the drm release.

**Comment by SoMuchForSubtlety** [comment] 2022-04-19 17:27
dupe of #223

**Closed as completed by SoMuchForSubtlety** 2022-04-19 17:27 UTC
Labels: bug
