### ISSUE TITLE
[BUG] The content must have a schedule that matches the current schedule filters

### ISSUE THREAD

**Issue by alanwHOME** [SoMuchForSubtlety/f1viewer#54] opened 2020-07-03 11:26 UTC
**Describe the bug**
Error received trying to playback anything from Austrian live event this weekend. Old content plays OK.
2020/07/03 12:13:49 [ERROR] got status 400 Bad Request with body:
{"skylark_error_code": null, "form_validation_errors": null, "error": "The content must have a schedule that matches the current schedule filters"}

**To Reproduce**
1. Go to: 2020 Austrian Grand Prix Formula 2 Practice 
Main Feed
│   ├──Play with MPV                                                                                                                                                                              
2. Try to play
3. See error: [ERROR] got status 400 Bad Request with body:
{"skylark_error_code": null, "form_validation_errors": null, "error": "The content must have a schedule that matches the current schedule filters"}

**Expected behaviour**
Playback to start in MPV player as per older items available to view.

**Screenshots**
![image](https://user-images.githubusercontent.com/47475582/86464835-4a3bdc80-bd28-11ea-86b5-e0d89643c5df.png)

**Desktop (please complete the following information):**
 - OS Win10 Pro 64bit
 - installation method: f1viewer_1.1.0_windows_64-bit.zip 
 - Version [Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:28:49Z]

**Logs**
2020/07/03 12:13:32 [INFO] logged in!
2020/07/03 12:13:32 [INFO] checking for live session
2020/07/03 12:13:49 [ERROR] got status 400 Bad Request with body:
{"skylark_error_code": null, "form_validation_errors": null, "error": "The content must have a schedule that matches the current schedule filters"}

**Comment by LsHallo** [comment] 2020-07-03 11:30
Duplicate of #53

**Comment by alanwHOME** [comment] 2020-07-03 11:32
Hi,
Loving the app. Thank you for writing such a great utility :-)
I used it all last season without issue, been using the new version for the past couple of weeks looking forward to the restart of this year's season but it won't play any of the new content for the Austrian GP today.

Thank and regards,

AlanwHOME

**Comment by LsHallo** [comment] 2020-07-03 11:34
Loving the app as well thanks @SoMuchForSubtlety ;)

**Comment by jfoster** [comment] 2020-07-03 11:36
Possible duplicate of #42

**Comment by SoMuchForSubtlety** [comment] 2020-07-08 19:19
This is likely because you don't have an access / pro account.
Closing the issue for now, if you think your account should be able to play it feel free to reopen the issue.

**Comment by MisaRistolainen** [comment] 2020-07-11 13:34
I have an F1TV pro account and I get this error

**Comment by LsHallo** [comment] 2020-07-11 13:51
Can you try with a vpn from a different country?

**Comment by MisaRistolainen** [comment] 2020-07-11 14:47
I'm using VPN from germany. Gabbing the m3u8 manually from the browser and opening it with streamlink works

**Comment by MisaRistolainen** [comment] 2020-07-11 15:16
Tried with a Swedish VPN aswell and same problem

**Comment by balexandre** [comment] 2020-07-18 19:04
@MisaRistolainen you can use streamlink in your config, like:

```json
{
  "title": "Stream with Streamlink+MPV",
  "command": ["streamlink", "--player", "C:\\ProgramData\\chocolatey\\lib\\mpv.install\\tools\\mpv.exe", "--hls-audio-select", "*", "$url", "1080p"]
		}
```

**Closed** 2021-06-24 20:05 UTC
Labels: bug
