### ISSUE TITLE
[BUG] $perspective doesn't work for World Feed

### ISSUE THREAD

**Issue by Macsim51** [SoMuchForSubtlety/f1viewer#217] opened 2022-03-25 01:20 UTC
Hi :)

I have a little bug with the _Custom Command_ (see below). I use $perspective for having a proper title on MPV, all works fine except for the main feed "World Feed", f1viewer start mpv without title : "--tittle="

With all others feeds (drivers, data, ...) it's ok (have tested with 2021 GP too and same bug).

But, maybe you can do this by default in f1viewer, no ? Because without this custom command, all opened MVP window have the same title (for example : "2022 Bahrain Grand Prix").

Thx for all your work :) :) :)

Windows 11 // f1viewer 2.6.0

```
[[custom_playback_options]]
	command = ["mpv", "$url", "--quiet", "--title=$perspective"]
	proxy = true
	title = "MPV with good title"
```

**Comment by SoMuchForSubtlety** [comment] 2022-03-26 18:27
dupe of #209

will be fixed in the next release

**Closed by SoMuchForSubtlety** 2022-03-26 18:27 UTC
Labels: bug
