### ISSUE TITLE
i can't watch Portimão TL1 live

### ISSUE THREAD

**Issue by EmanuelTenorio** [SoMuchForSubtlety/f1viewer#136] opened 2021-04-30 10:43 UTC
![image](https://user-images.githubusercontent.com/81625357/116684712-a642b200-a987-11eb-8bfb-384323d61430.png)

**Comment by SkYNewZ** [comment] 2021-04-30 10:44
Duplicate of https://github.com/SoMuchForSubtlety/f1viewer/issues/135

**Closed** 2021-04-30 18:59 UTC
Labels: bug
