### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bubba14** [SoMuchForSubtlety/f1viewer#172] opened 2021-06-14 23:40 UTC
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
does not allow the video to be played 

**To Reproduce**
1. logging in (you get an immediate connection error) 
2. click to play any video or copy  any video URL 
3. you get a token error for the URL and video

**Expected behavior**
for the video to pop up and to start playing

**Screenshots**
1st error: ![Screen Shot 2021-06-14 at 6 34 13 PM](https://user-images.githubusercontent.com/85909099/121971789-3160e700-cd3f-11eb-8a94-407fac2d945c.png)

2nd error: 
![Screen Shot 2021-06-14 at 6 34 31 PM](https://user-images.githubusercontent.com/85909099/121971801-3756c800-cd3f-11eb-825f-636acc313eb2.png)
**F1TV account plan**

Do you have a free, access or pro account? Are you using a VPN / proxy?
I have a pro account and live in America. No proxy/VPN

**Desktop (please complete the following information):**
 - OS: Mac
 - installation method: Through brewer and downloading both mac files
 - Version [f1viewer 2.01]

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by PhillipAlpha** [comment] 2021-06-15 08:30
I too have a similar issue on Windows 10

**Comment by gustaferiksson** [comment] 2021-06-15 09:32
@Bubba14 check already existing issues before creating new ones. #167 already mention this.

**Comment by Bubba14** [comment] 2021-06-15 17:48
> @Bubba14 check already existing issues before creating new ones. #167 already mention this.

correct but I'm also getting a second error that the other one does not talk about

**Comment by gustaferiksson** [comment] 2021-06-15 18:29
@Bubba14 It's obviously a related error so you should add that information to the first issue. You haven't even written a descriptive title and just slapped the author as an assignee... That's not how you get this busy chap to resolve the issue. If you want to contribute, close this issue, find out what the problem is, fix it and create a PR but by looking at the quality of your issue you probably don't know how to.

**Comment by QGJ37** [comment] 2021-06-18 09:53
Same problem here.

The app loose the Password/Login at each launch and once logged in, have this error:
![image](https://user-images.githubusercontent.com/64592000/122542966-92ccd280-d02b-11eb-9834-2990a83ada0b.png)

Using Version 2.0.1 on Windows 10 with a Pro account without any VPN (living in France).

**Comment by OGKevin** [comment] 2021-06-18 10:05
This is fixed in #171

**Comment by SoMuchForSubtlety** [comment] 2021-06-24 20:24
sorry for the delay, fixed in the latest release https://github.com/SoMuchForSubtlety/f1viewer/releases/tag/v2.1.0

**Closed** 2021-06-24 20:24 UTC
Labels: bug
