### ISSUE TITLE
Error 401 Unauthorized 

### ISSUE THREAD

**Issue by RiffleMan** [SoMuchForSubtlety/f1viewer#62] opened 2020-07-04 10:06 UTC
I have problem with logging in. What login and password should I enter in the app to log in?

**Comment by SoMuchForSubtlety** [comment] 2020-07-04 10:49
Log in using your F1TV email and password.

**Comment by Hanswurst02** [comment] 2020-07-04 11:04
I have the same problem. 
VPN is disabled.

**Comment by SoMuchForSubtlety** [comment] 2020-07-04 15:16
dupe of #60 
I will try to help there

**Closed by SoMuchForSubtlety** 2020-07-04 15:16 UTC
Labels: question
