### ISSUE TITLE
[BUG] Error opening livestream in Quicktime Player on non-M1 Mac

### ISSUE THREAD

**Issue by Chassmann** [SoMuchForSubtlety/f1viewer#235] opened 2022-04-08 13:10 UTC
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Opening streams in Quicktime Player on Mac BigSur 11.6 (non-M1 chip mac) results in error pop-up; "The document "index.mpd" couldn't be opened. This file isn't compatible with Quicktime Player."

**To Reproduce**
1. Log in to F1Viewer with username and newly added token key
2. Try to play live stream in quicktime
3. See error described above

**F1TV account plan**
No VPN, Pro F1TV

**Desktop (please complete the following information):**
 - BigSur 11.6
 - MacOS package
 - Version 2.7

**Comment by TonyJ24** [comment] 2022-04-09 05:20
Having the exact same issue, using an M1 MacBook Air.

**Comment by pedrodonkey** [comment] 2022-04-09 05:26
Same issue on an intel iMac too.

macOS Monterey 12.3
f1viewer 2.7.0

**Comment by callumparr** [comment] 2022-04-09 05:43
Also having the same issue. I think f1viewer has been kneecapped by F1TV. I've tried VLC on MacOS as well to no avail.

**Comment by callumparr** [comment] 2022-04-09 05:46
probably related to this issue and DRM crack down

**Comment by bviolier** [comment] 2022-04-09 05:55
To add one, I also got the same issue on the M1, but with `mpv`. The screen is just grey and the console is full of errors:
- https://capture.dropbox.com/g6dVLq9hVtJEWK9H
- https://capture.dropbox.com/J4NJFQkLRlJoKb9l

Seems there is more errors at the start, but it's going to fast to see them and I can't find them back (it's not stored in the f1viewer logs).

Edit: seems it's this: https://github.com/SoMuchForSubtlety/f1viewer/issues/233

**Comment by myneckiskillingme** [comment] 2022-04-09 06:04
> 

I also have this same exact issue. M1 macbook too.

There are a bunch of errors going quite fast. seems like most of them are about decoding audio though.

**Comment by bviolier** [comment] 2022-04-09 06:40
Just FYI: It's because they added DRM to the streams, see https://github.com/SoMuchForSubtlety/f1viewer/issues/233.

A "temporary", very manual solution for now seems to be to use the Firefox "picture in picture" option. You can somehow replicate what we had, although it seems to be harder on laptop performance.

**Comment by antonpolishko** [comment] 2022-04-09 06:41
macbook 12 (2017), latest updates. Same issues.

`vlc`, `quicktime` - no stream open 
`iina` - grey screen with artifacts.

**Comment by Robertsmania** [comment] 2022-04-09 06:46
I see the same behavior on my MacBook Pro but also am unable to open streams on my Windows 10 PC with VLC.  Token is accepted and verified, but trying to open any qualify stream sits on the VLC player for a few moments and then spews errors about no start time and invalid frame.

**Comment by SoMuchForSubtlety** [comment] 2022-04-19 17:28
dupe of #233, F1TV implemented DRM for livestreams

**Closed as completed by SoMuchForSubtlety** 2022-04-19 17:28 UTC
Labels: bug
