### ISSUE TITLE
[BUG] No config file created (macOS)

### ISSUE THREAD

**Issue by JipG1** [SoMuchForSubtlety/f1viewer#129] opened 2021-04-17 21:48 UTC
Hi.

I have successfully installed f1viewer on my Mac mini M1 with home-brew. I can start it up with the terminal, log in and watch a stream. For some reason, the application didn't create a config file or a 'f1viewer' folder in $HOME/Library/Application Support. I have started the application multiple times, but no config file gets created. When I create one myself, it doesn't do anything so I guess the application needs to create one self. 

Is there something I'm doing wrong with the installation? When I boot f1viewer without home-brew and just from the binary directly, it still doesn't create a config file. 

Thx for the help.

**Comment by SoMuchForSubtlety** [comment] 2021-04-17 22:48
dupe of #123

I currently don't have access to an m1 mac to build f1viewer. You have to build it yourself until I find a solution.

**Closed by SoMuchForSubtlety** 2021-04-17 22:48 UTC
Labels: bug
