### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kareltje1980** [SoMuchForSubtlety/f1viewer#50] opened 2020-07-02 15:47 UTC
The exact error: tls: handshake failed: error:14FFF3E7:SSL routines:(UNKNOWN)SSL_internal:unknown failure occurred 

MPV sometimes has issues with some stream (2020-any race-Main Feed). It gives an TLS error. Tried this with the most recent MPV and f1Viewer. 

My suggestion would be to switch to VLC, or make it possible to choose the rendered in the config.json file.

**Comment by balexandre** [comment] 2020-07-02 15:56
would love to at least have the option to use VLC instead...

**Comment by ragnos** [comment] 2020-07-02 18:38
Can't reconstruct that error, but then again you didn't mention your platform. Haven't had an issue on Windows 10 1909.

@balexandre Just add it to your config.json:

``"custom_playback_options": [
		{
			"title": "Stream on VLC",
			"command": ["C:\\Tools\\VLC\\vlc.exe", "$url"]
		}
],``

_Your path to VLC.exe is propably different. Backslashes need to be escaped with an additional Backslash._

**Comment by nmussy** [comment] 2020-07-03 07:38
I'm getting the same error with MPV on full races and live sessions. Paddock Pass works fine, I'm guessing it's an issue with the `f1tv-cdn-cent-live.formula1.com` domain certificate.

```
[f1viewer]$ mpv https://f1tv-cdn-cent-live.formula1.com/ondemand/f3d9/_C_/3/2/wif0315183647/1/clip_2_master.m3u8?nva=1593761836&ttl=86400&cc=FR&token=0dd526f 
 tls: handshake failed: error:14FFF3E7:SSL routines:(UNKNOWN)SSL_internal:unknown failure occurred
Failed to open https://f1tv-cdn-cent-live.formula1.com/ondemand/f3d9/_C_/3/2/wif0315183647/1/clip_2_master.m3u8?nva=1593761836&ttl=86400&cc=FR&token=0dd526f5
 tls: handshake failed: error:14FFF3E7:SSL routines:(UNKNOWN)SSL_internal:unknown failure occurred
Failed to open https://f1tv-cdn-cent-live.formula1.com/ondemand/f3d9/_C_/3/2/wif0315183647/1/clip_2_OTT_F1_WIF_VIDEO_6_5500000.m3u8.
EDL: Could not open source file 'https://f1tv-cdn-cent-live.formula1.com/ondemand/f3d9/_C_/3/2/wif0315183647/1/clip_2_OTT_F1_WIF_VIDEO_6_5500000.m3u8'.
No video or audio streams selected.

Exiting... (Errors when loading file)

[f1viewer]$ mpv https://f1vod.formula1.com/f1vodprod/331/972/1593731612908/2001_AUSTRIA_THURS_PADDOCK_PASS_F1TV-511448133064-master.m3u8?e=1593762331&a=FR&h=     Video --vid=1 'bitrate 1653000' (h264 768x432 25.000fps)
	Video --vid=2 'bitrate 374000' (h264 512x288 25.000fps)
	Video --vid=3 'bitrate 715000' (h264 512x288 25.000fps)
	Video --vid=4 'bitrate 1080000' (h264 768x432 25.000fps)
	Video --vid=5 'bitrate 2532000' (h264 1024x576 25.000fps)
	Video --vid=6 'bitrate 4513000' (h264 1280x720 25.000fps)
(+) Video --vid=7 'bitrate 7661000' (h264 1920x1080 25.000fps)
	Audio --aid=1 'bitrate 1653000' (aac 2ch 44100Hz)
	Audio --aid=2 'bitrate 374000' (aac 2ch 44100Hz)
	Audio --aid=3 'bitrate 715000' (aac 2ch 44100Hz)
	Audio --aid=4 'bitrate 1080000' (aac 2ch 44100Hz)
	Audio --aid=5 'bitrate 2532000' (aac 2ch 44100Hz)
	Audio --aid=6 'bitrate 4513000' (aac 2ch 44100Hz)
(+) Audio --aid=7 'bitrate 7661000' (aac 2ch 44100Hz)
AO:  48000Hz stereo 2ch float
VO:  1920x1080 yuv420p
```

**Comment by balexandre** [comment] 2020-07-03 07:53
@nmussy can you specify the race you are having issues with? 

just seeing the current live stream without an issue:

![](https://i.imgur.com/n5GXHOX.png)

**Comment by nmussy** [comment] 2020-07-03 07:56
I was talking about the same live session, yes:

![image](https://user-images.githubusercontent.com/2505696/86445778-481b5300-bd13-11ea-9e7e-70062059dfd0.png)

Could you check whether we're getting the same m3u8 URL?

`https://f1tv-cdn-cent-live.formula1.com/live/wif0702172559/master.m3u8`

**Comment by balexandre** [comment] 2020-07-03 07:58
@nmussy ahh got it, it's an issue with MPV, try install VLC and use the config that @ragnos gave in the answer above and you will be able to see everything 😊👌

![image](https://user-images.githubusercontent.com/45473/86446076-bb24c980-bd13-11ea-8cbc-145220cda311.png)

**Comment by TheDevFreak** [comment] 2020-07-03 08:02
Also getting the same errors, it is a shame since mpv is far better than VLC.

**Comment by balexandre** [comment] 2020-07-03 08:08
here's a small video with MPV and VLC streaming the exact same stream

[https://youtu.be/0aL9x47-37E](https://youtu.be/0aL9x47-37E)

**Comment by nmussy** [comment] 2020-07-03 08:10
Yeah confirmed, it's an MPV issue, VLC works fine.

And I do have and use Windows Terminal, I haven't looked into why f1viewer is launching cmd 😄

**Comment by ragnos** [comment] 2020-07-03 08:12
Just for the record, mpv is working perfectly for me right now. What versions are you guys running?

```powershell
PS D:\mpv> .\mpv.com --version
mpv 0.32.0-563-gdc24a437fb Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 21 22:18:57 +08 2020
FFmpeg library versions:
   libavutil       56.55.100
   libavcodec      58.93.100
   libavformat     58.47.100
   libswscale      5.8.100
   libavfilter     7.86.100
   libswresample   3.8.100
FFmpeg version: git-2020-06-21-842bc312a
```

**Comment by nmussy** [comment] 2020-07-03 08:13
Mine's from the latest choco package:

```
mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015
```

**Comment by balexandre** [comment] 2020-07-03 08:13
@ragnos on Windows 10 2004

```bash
C:\Users\balex> mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

```

**Comment by Kareltje1980** [comment] 2020-07-03 08:19
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

**Comment by ragnos** [comment] 2020-07-03 08:21
Well there is your issue. Seems like the TLS implementation in that stable build of mpv is broken, Use the git version for now.

https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200621-git-dc24a43.7z/download

**Comment by TheDevFreak** [comment] 2020-07-03 08:27
Confirmed the build that @ragnos linked fixes the issue.

**Comment by nmussy** [comment] 2020-07-03 08:41
Confirmed, we can probably close this issue now

**Comment by SoMuchForSubtlety** [comment] 2020-07-03 11:48
Does VLC work now? I added MPV as default because VLC did not support HLS streams with multiple audio and video tracks.

**Comment by ragnos** [comment] 2020-07-03 12:28
VLC did atleast took it this morning. Starting with F3 Quali F1TV ran in some issues where the master.m3u8 wasn't available (returning 404) and they switched the CDN back and forth. Now VLC doesn't work for me anymore, mpv holds up.

[vlc.log](https://github.com/SoMuchForSubtlety/f1viewer/files/4869678/vlc.log)

**Comment by balexandre** [comment] 2020-07-03 14:11
F1TV had issues for this current session (FP2, Austria 2020, 1st race) as you can confirm with [Reddit](https://www.reddit.com/r/F1TV/comments/hkiped/not_even_sunday_and_its_already_dead/) 

a lot of timeouts for several persons... not all though... I just don't want to imagine Sunday's race, I hope they fix everything before the race

**Closed** 2020-07-03 18:56 UTC
Labels: bug
