### ISSUE TITLE
No livestreams showing

### ISSUE THREAD

**Issue by jester-xbmc** [SoMuchForSubtlety/f1viewer#135] opened 2021-04-30 10:36 UTC
Hi,

it looks like they switched to API V2 as I currently don't see the livestreams, although on the website the livestreams are showing up
I see you pushed V2 API updates in your latest commit, could you kindly compile a new release based on this ?

Thanks

**Comment by SkYNewZ** [comment] 2021-04-30 10:49
If you are familiar not familiar with command lines, you can :

```shell
git clone https://github.com/SoMuchForSubtlety/f1viewer
cd f1viewer
go build -v -o f1viewer cmd/main.go 
./f1viewer
```

This obviously works 😉

**Comment by jester-xbmc** [comment] 2021-04-30 10:55
I am, and can compile but I meant "in general" ;-)

**Comment by charlesomer** [comment] 2021-04-30 11:07
Looks like you must be signed into an account with an active subscription now too (as expected).

**Comment by virus0822** [comment] 2021-04-30 12:08
> 
> 
> If you are familiar not familiar with command lines, you can :
> 
> ```shell
> git clone https://github.com/SoMuchForSubtlety/f1viewer
> cd f1viewer
> go build -v -o f1viewer cmd/main.go 
> ./f1viewer
> ```
> 
> This obviously works 😉

I'm not familiar with command lines... How can I do that ? 😅 
Btw i'm on windows 10

**Comment by storki93** [comment] 2021-04-30 12:23
Me neither, but happy to see you guys already working to fix this. Cant believe that yet again the F1 TV API has changed with no notice. They don’t seem to care about third party applications at all. I’ll wait for an update, hopefully soon :)

**Comment by SkYNewZ** [comment] 2021-04-30 12:40
@virus0822 Explaining how to set this up on Windows if you don't have Go installed would take too long. You can start by looking here https://golang.org/dl/ if you want to do it yourself. Then, via a command prompt or PowerShell window, you could run the commands listed above.

In any case, here are the binaries you can download and run that I compiled manually on my side: https://drive.google.com/drive/folders/1-a45g2aXijXF4fR0WTdkqM8RLJBOZqoT?usp=sharing



> Me neither, but happy to see you guys already working to fix this. Cant believe that yet again the F1 TV API has changed with no notice. They don’t seem to care about third party applications at all. I’ll wait for an update, hopefully soon :)

@storki93 They clearly don't care about third party applications, but it's also normal, it's none of their business and it's a "backdoor" way to consume their service.

**Comment by virus0822** [comment] 2021-04-30 13:46
> 
> 
> @virus0822 Explaining how to set this up on Windows if you don't have Go installed would take too long. You can start by looking here https://golang.org/dl/ if you want to do it yourself. Then, via a command prompt or PowerShell window, you could run the commands listed above.
> 
> In any case, here are the binaries you can download and run that I compiled manually on my side: https://drive.google.com/drive/folders/1-a45g2aXijXF4fR0WTdkqM8RLJBOZqoT?usp=sharing
> 
> > Me neither, but happy to see you guys already working to fix this. Cant believe that yet again the F1 TV API has changed with no notice. They don’t seem to care about third party applications at all. I’ll wait for an update, hopefully soon :)
> 
> @storki93 They clearly don't care about third party applications, but it's also normal, it's none of their business and it's a "backdoor" way to consume their service.

I've downloaded the f1viewer_windows_amd64.exe file, but when i click on it nothing happens 😕

**Comment by jagr200** [comment] 2021-04-30 14:10
> @virus0822 Explaining how to set this up on Windows if you don't have Go installed would take too long. You can start by looking here https://golang.org/dl/ if you want to do it yourself. Then, via a command prompt or PowerShell window, you could run the commands listed above.
> 
> In any case, here are the binaries you can download and run that I compiled manually on my side: https://drive.google.com/drive/folders/1-a45g2aXijXF4fR0WTdkqM8RLJBOZqoT?usp=sharing
Attach files by dragging & dropping, selecting or pasting them.

> 
> > Me neither, but happy to see you guys already working to fix this. Cant believe that yet again the F1 TV API has changed with no notice. They don’t seem to care about third party applications at all. I’ll wait for an update, hopefully soon :)
> 
> @storki93 They clearly don't care about third party applications, but it's also normal, it's none of their business and it's a "backdoor" way to consume their service.

Still doesnt work. No video feeds other than the main feed are allowed to be selected.

At this point this viewer is dead. Not updated to the 50fps API and no longer working as intended. Shame

**Comment by SkYNewZ** [comment] 2021-04-30 14:20
> Still doesnt work. No video feeds other than the main feed are allowed to be selected.
> 
> At this point this viewer is dead. Not updated to the 50fps API and no longer working as intended. Shame

lol, go into http://f1tv.formula1.com/ if it's a "shame".

By building the `master` branch like a did, I have 50fps 1080p but indeed, I only have the main feed.
<img width="859" alt="image" src="https://user-images.githubusercontent.com/26750012/116707935-1d4b6b00-a9c7-11eb-8a68-bfe6fed8b029.png">

**Comment by jagr200** [comment] 2021-04-30 14:22
> > Still doesnt work. No video feeds other than the main feed are allowed to be selected.
> > At this point this viewer is dead. Not updated to the 50fps API and no longer working as intended. Shame
> 
> lol, go into http://f1tv.formula1.com/ if it's a "shame".
> 
> By building the `master` branch like a did, I have 50fps 1080p but indeed, I only have the main feed.
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/26750012/116707935-1d4b6b00-a9c7-11eb-8a68-bfe6fed8b029.png">

So you saying it works is false. Because it absolutely does not work. It only allows the main feed and ignores all other settings and feeds. It is a shame that support has been discontinued for this viewer as it was easily the best out there. I've now switched to RaceControl because while it isn't as good as F1TVViewer it does actually work right now.

**Comment by storki93** [comment] 2021-04-30 14:27
@jagr200 Bro it’s a free third party application that’s made by an amazing F1 Fan and developed with help of some genius minds in the F1 Community. I don’t think it’s right to be mad at @SoMuchForSubtlety Jakob or anyone who works on this project. 

It’s time to appreciate and you can see in the Issue Section on GitHub that there’s a lot of work and improvements going on. Just give them some time and I’m sure it will be fixed. Go to whatever player you want to use instead in the meantime.

**Comment by SkYNewZ** [comment] 2021-04-30 14:28
@jagr200 I don't deny it and I see it as you do, f1viewer doesn't work as it used to.

It is still a great project, the best in my opinion and in your opinion.

However, the support is not "stopped" as you claim. Just look at the commits history which you can find here https://github.com/SoMuchForSubtlety/f1viewer/commit/43a984dd7c2644490e48f8de500085d6b308e89b. The last one was 3 hours ago...

Finally, this is a FREE community project. So please have a little tolerance for an unpaid, passionate developer who agrees to share his work with us, which he could have kept for his personal use.

**Comment by storki93** [comment] 2021-04-30 14:29
@SkYNewZ i would love to know how to do this. Unfortunately I missed most coding classes at school. Sadge. 😂

**Comment by jagr200** [comment] 2021-04-30 14:33
> @jagr200 Bro it’s a free third party application that’s made by an amazing F1 Fan and developed with help of some genius minds in the F1 Community. I don’t think it’s right to be mad at @SoMuchForSubtlety Jakob or anyone who works on this project.
> 
> It’s time to appreciate and you can see in the Issue Section on GitHub that there’s a lot of work and improvements going on. Just give them some time and I’m sure it will be fixed. Go to whatever player you want to use instead in the meantime.

Y'all are too sensitive. Who said I was mad? Just stating a fact that support has tapered off on this. As stated by the developer previously in other issue requests.

**Comment by SkYNewZ** [comment] 2021-04-30 14:35
I present to you the latest commit 43a984d that has just been pushed !
<img width="346" alt="image" src="https://user-images.githubusercontent.com/26750012/116710239-6ef4f500-a9c9-11eb-8ef2-32679d60d8e5.png">

Thanks @SoMuchForSubtlety to be so reactive !

**Comment by storki93** [comment] 2021-04-30 14:36
> > @jagr200 Bro it’s a free third party application that’s made by an amazing F1 Fan and developed with help of some genius minds in the F1 Community. I don’t think it’s right to be mad at @SoMuchForSubtlety Jakob or anyone who works on this project.
> > It’s time to appreciate and you can see in the Issue Section on GitHub that there’s a lot of work and improvements going on. Just give them some time and I’m sure it will be fixed. Go to whatever player you want to use instead in the meantime.
> 
> Y'all are too sensitive. Who said I was mad? Just stating a fact that support has tapered off on this. As stated by the developer previously in other issue requests.

But saying the “viewer is dead” and that it is a “shame” is simply wrong. I wouldn’t even be mad if the player would for ever stay the same as it is now, because it’s a FREE product. The alternative offered by F1 is their player and that is the worst and you know it.

**Comment by storki93** [comment] 2021-04-30 14:36
> I present to you the latest commit [43a984d](https://github.com/SoMuchForSubtlety/f1viewer/commit/43a984dd7c2644490e48f8de500085d6b308e89b) that has just been pushed !
> <img alt="image" width="346" src="https://user-images.githubusercontent.com/26750012/116710239-6ef4f500-a9c9-11eb-8ef2-32679d60d8e5.png">
> 
> Thanks @SoMuchForSubtlety to be so reactive !

W

**Comment by Koko2411** [comment] 2021-04-30 14:38
> 
> 
> > I present to you the latest commit [43a984d](https://github.com/SoMuchForSubtlety/f1viewer/commit/43a984dd7c2644490e48f8de500085d6b308e89b) that has just been pushed !
> > <img alt="image" width="346" src="https://user-images.githubusercontent.com/26750012/116710239-6ef4f500-a9c9-11eb-8ef2-32679d60d8e5.png">
> > Thanks @SoMuchForSubtlety to be so reactive !
> 
> W

how to run it?

**Comment by SkYNewZ** [comment] 2021-04-30 14:43
Run these binaries as usual [build-43a984d.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6406113/build-43a984d.zip)

**Comment by SkYNewZ** [comment] 2021-04-30 14:49
@jagr200 You can see development status regarding the new API in #120

**Comment by jester-xbmc** [comment] 2021-04-30 14:50
> 
> 
> Run these binaries as usual [build-43a984d.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6406113/build-43a984d.zip)

This windows binary (and i'm trying to debug but i'm a C++ guy, i'm a go n00b) is causing -> panic: runtime error: invalid memory address or nil pointer dereference

**Comment by jester-xbmc** [comment] 2021-04-30 14:55
try this bin for windows

**Comment by jester-xbmc** [comment] 2021-04-30 14:57
Try this windows binary..
[f1viewer-v2api.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6406227/f1viewer-v2api.zip)

**Comment by virus0822** [comment] 2021-04-30 15:00
> 
> 
> Try this windows binary..
> [f1viewer-v2api.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6406227/f1viewer-v2api.zip)

Replays work well but i get this message when i click on live sessions 
![image](https://user-images.githubusercontent.com/83455367/116714013-9a7ddc80-a9d5-11eb-99d4-aa0a4da3c9ec.png)

**Comment by jester-xbmc** [comment] 2021-04-30 15:04
Updated:

Try this windows binary..
[f1viewer-v2api.zip](https://github.com/SoMuchForSubtlety/f1viewer/files/6406262/f1viewer-v2api.zip)

**Comment by virus0822** [comment] 2021-04-30 15:05
Nothing happens when i click on it now 😕

**Comment by charlesomer** [comment] 2021-04-30 19:59
Looks like the folder structure is a little weird?
Multiple copies of the same GP etc.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/32498151/116748140-e8efa300-a9f6-11eb-8340-b42df70b6e17.png">

**Comment by charlesomer** [comment] 2021-04-30 20:59
> > Looks like the folder structure is a little weird?
> > Multiple copies of the same GP etc.
> > <img alt="image" width="202" src="https://user-images.githubusercontent.com/32498151/116748140-e8efa300-a9f6-11eb-8340-b42df70b6e17.png">
> 
> Currently, I just copy the F1TV homepage 1:1, I will add move content from the new API and organize it better in the future.

Ah I see that makes sense! Other than that it looks like it works really well 👏

**Comment by SoMuchForSubtlety** [comment] 2021-04-30 20:59
> > I'm working on a new release and hope to get it out before the race.
> > The new API is stricter with authentication and subscriptions, so don't be surprised if streams don't work any more for non F1TV Pro accounts. I'll try my best to continue supporting the legacy API too.
> 
> Thanks for your work, indeed I used the action compiler for the bin I post above, so far it looks ok, will test during FP3 tomorrow
> 
> P.S. with some bins I get this runtime error:
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x20 pc=0x103679f]
> 
> ...

Do you get this error with the latest version? does it happen every time?

**Comment by jester-xbmc** [comment] 2021-04-30 21:01
> 
> 
> > > I'm working on a new release and hope to get it out before the race.
> > > The new API is stricter with authentication and subscriptions, so don't be surprised if streams don't work any more for non F1TV Pro accounts. I'll try my best to continue supporting the legacy API too.
> > 
> > 
> > Thanks for your work, indeed I used the action compiler for the bin I post above, so far it looks ok, will test during FP3 tomorrow
> > P.S. with some bins I get this runtime error:
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal 0xc0000005 code=0x0 addr=0x20 pc=0x103679f]
> > ...
> 
> Do you get this error with the latest version? does it happen every time?

I'm trying to narrow down why this is happening, previous binary I posted worked before, but now gives a similar runtime error, also the latest now does it...curious

**Comment by SoMuchForSubtlety** [comment] 2021-04-30 21:44
the latest commit fixes the issue

https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/800793076

**Comment by jester-xbmc** [comment] 2021-04-30 21:52
> 
> 
> the latest commit fixes the issue
> 
> https://github.com/SoMuchForSubtlety/f1viewer/actions/runs/800793076

Yup, fixed, thanks !

P.S. with the switch to V2 API we seem to have lost 1080p resolution, we only have 720p at 50fps, this is correct ? or is there a way to get the 1080p 25 fps link back ?

**Comment by charlesomer** [comment] 2021-04-30 22:19
VLC reports 1080p for me (I think it's 50fps), I don't think any of the live streams will be 25fps from now on unfortunately.

**Comment by jester-xbmc** [comment] 2021-04-30 22:27
> 
> 
> VLC reports 1080p for me (I think it's 50fps), I don't think any of the live streams will be 25fps from now on unfortunately.

It seems the on-boards are 720p at 50fps, the world feed is indeed 1080p at 50fps

**Comment by charlesomer** [comment] 2021-04-30 22:33
Ah yes I see now, 'legacy content' has 1080p25 streams for the on-boards. I thought on boards were only 720p though anyway so maybe it was upscaling and now F1 is just leaving it at 720p. I could be wrong though.

**Comment by SoMuchForSubtlety** [comment] 2021-05-01 13:03
I just release 2.0, please report any issues or bugs you find.

**Closed by SoMuchForSubtlety** 2021-05-01 13:03 UTC
Labels: bug

**Comment by SkYNewZ** [comment] 2021-05-01 17:04
> I'm working on a new release and hope to get it out before the race.
> 
> 
> 
> The new API is stricter with authentication and subscriptions, so don't be surprised if streams don't work any more for non F1TV Pro accounts. I'll try my best to continue supporting the legacy API too.

Streams was working before without any F1TV pro account ? 😮

**Comment by slyvioborin** [comment] 2021-05-01 22:04
> > I'm working on a new release and hope to get it out before the race.
> > The new API is stricter with authentication and subscriptions, so don't be surprised if streams don't work any more for non F1TV Pro accounts. I'll try my best to continue supporting the legacy API too.
> 
> Streams was working before without any F1TV pro account ? 😮

Yes, but sadly not anymore
