### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tunkar** [SoMuchForSubtlety/f1viewer#221] opened 2022-03-26 22:47 UTC
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**
Instead of the George Russel stream it shows Alex Albon.

**To Reproduce**
1. Go to...
Any Live & Replays section
2. Try to play...
George Russell stream
3. See error
The stream showed is that of Albon's
**Expected behaviour**
The Russell stream is the expected behaviour.

**Screenshots**

**F1TV account plan**
PRO Account

**Desktop (please complete the following information):**
 - OS Windows 10
 - installation method
 - Version [`f1viewer -v` output] latest (today's)

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.

**Comment by SoMuchForSubtlety** [comment] 2022-03-27 16:06
dupe of #222

**Closed by SoMuchForSubtlety** 2022-03-27 16:06 UTC
Labels: bug
