### ISSUE TITLE
F1viewer crash on startup

### ISSUE THREAD

**Issue by gaeldemarseille** [SoMuchForSubtlety/F1viewer#22] opened 2019-10-26 22:53 UTC
```
panic: runtime error: index out of range

goroutine 19 [running]:
main.getLiveNode(0xc000161fb0, 0x1, 0x1, 0x0)
        C:/Users/jakob/Documents/projects/F1/F1viewer/node.go:57 +0x72f
main.main.func1(0xc00012f2d0, 0xc000136000)
        C:/Users/jakob/Documents/projects/F1/F1viewer/main.go:128 +0x9b
created by main.main
        C:/Users/jakob/Documents/projects/F1/F1viewer/main.go:125 +0x5fc
```

**Comment by fictionalname** [comment] 2019-10-27 07:23
Hello,

I'm getting exactly the same issue.  It was working perfectly yesterday afternoon.  I've done the usual reboots, updates, etc.

Details from debug mode:
panic: runtime error: index out of range

goroutine 19 [running]:
main.getLiveNode(0xc00014dfb0, 0x1, 0x1, 0x0)
	e.go:f

Hope you can get a fix soon.

Thanks muchly!

**Comment by Joshimuz** [comment] 2019-10-27 08:21
Seems to be an issue with the checking of a live session.
Commenting out lines 50-53 and 56-62 in node.go fixes the issue, but just disables the checking of a live node.

For some reason "item.ContentURL.Items[0].ContentURL.Self" in "getLiveNode()" is giving an array with no elements, which gives an index out of range exception. 

Adding "if len(item.ContentURL.Items) > 0 {" again fixes the issue.

I have no idea how any of this works so I don't want to make a Pull Request or anything, the problem is obviously in "getHomepageContent()"'s handling of the F1TV's json.

**Comment by SoMuchForSubtlety** [comment] 2019-10-27 08:24
thanks for the report, I'll take a look

**Comment by SoMuchForSubtlety** [comment] 2019-10-27 08:40
should be fixed fixed :) https://github.com/SoMuchForSubtlety/F1viewer/releases/tag/v0.7.3

**Closed** 2019-10-27 09:32 UTC

**Comment by fictionalname** [comment] 2019-10-27 12:37
Awesome work, thanks for the quick fix!!  :D 

👍
