### ISSUE TITLE
[BUG] tls: handshake failed

### ISSUE THREAD

**Issue by holayhey** [SoMuchForSubtlety/f1viewer#64] opened 2020-07-04 14:00 UTC
**Describe the bug**
I get the following error when trying to play "2020 Austrian Grand Prix Formula 1 Qualifying - LIVE". The issue happens when trying to play any of the live feeds (main, driver, pit lane, ...). VODs play fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/67830994/86513948-8b0e2100-be0e-11ea-9dc7-5db6f7646754.png)

**F1TV account plan**
F1TV Pro, the live feed plays fine in a browser on the same machine.

**Desktop (please complete the following information):**
Windows 10, F1Viewever downloades as a precompiled binery from this repo, MPV and youtube-dl installed via Chocolatey and added to PATH.
```
Version:     1.1.0
Git commit:  b6963937df1c3608c3bbf0cbc09cf28123893564
Built:       2020-06-29T15:28:49Z
```

**Logs**
This is the entire log file:
```
2020/07/04 15:39:45 [INFO] logged in!
2020/07/04 15:39:45 [INFO] checking for live session
2020/07/04 15:44:42 [INFO] logged in!
2020/07/04 15:44:42 [INFO] checking for live session
```

**Comment by TheDevFreak** [comment] 2020-07-04 14:59
https://github.com/SoMuchForSubtlety/f1viewer/issues/50#issuecomment-653419892

See linked comment.

**Comment by SoMuchForSubtlety** [comment] 2020-07-04 15:13
Yes this is a dupe of #50 

The issue is with mpv, this comment has a solution https://github.com/SoMuchForSubtlety/f1viewer/issues/50#issuecomment-653419892

**Closed by SoMuchForSubtlety** 2020-07-04 15:13 UTC
Labels: bug
